### ISSUE TITLE
Parameter Selection

### ISSUE THREAD

**Issue by radio1988** [Vivianstats/scImpute#12]
With scImpute, how can we select parameters for `drop_thre` and `Kclusters`?
Should we always use the default?
Thanks!

**Comment by Vivianstats** [comment]
Hello,

For `drop_thr`e, I suggest that you start with 0.5 and in most cases, it works pretty well.

As for `Kclusters`, you can perform an initial clustering of the raw data, and hopefully, that gives you a vague idea of the approximate number of clusters in your data. A smaller `Kclusters` makes scImpute more conservative.

Best,
Vivian
