### ISSUE TITLE
Overestimation with new version

### ISSUE THREAD

**Issue by Nak0r** [Vivianstats/scImpute#13]
Hi,

I recently tried your newest version (v0.0.6) on my data but I encountered some problem. My experiment consists in taking an actual dataset, masking a part of its value(artificially setting to 0) and see if scImpute successfully recovers the data. 
However, I could not make it work and maybe I did something wrong (like some preprocessing steps). I used K=1 and default parameters.
Do you have an idea about this issue? Here is what I observe:

![image](https://user-images.githubusercontent.com/29566937/38230297-d4115ae2-36a8-11e8-9c03-5608f1d87fed.png)

Thanks

**Comment by Vivianstats** [comment]
Hello Nak0r,

I'd like to ask a few questions to help me identify the problem.

Do you have the same problem with v0.0.5 or previous versions?
Are the masked values randomly selected? Are there already dropouts before you manually introduce 0s?
Can I take a look at the plot on the log10 scale?

Thanks,
Vivian

**Comment by Vivianstats** [comment]
Hello Cedric,

Thanks for sending me the information.

Just to make sure that I understand correctly, you first masked the values and then extract 2000 genes. So the input for scImpute is a count matrix with 2000 rows? Also, have you investigated the raw data and is it safe to assume a single population?

Best,
Vivian

**Comment by Vivianstats** [comment]
Hello Cedric,

I have tested your example dataset and I think there are two things you may try to improve the results.

First, we recommend using the whole-genome matrix (with at least 10,000 genes) and this ensures that identification of dropouts is robust.

Second, I have made slight changes to the algorithm to avoid extreme values in regression. So you can reinstall scImpute from Github and  should be able to obtain a comparison like
![scatter](https://user-images.githubusercontent.com/25557722/38448394-b58741c8-39b8-11e8-8f8a-b1d108f7d005.png)

Hopefully, you can get even better results when you try the whole-genome matrix.

Best,
Vivian

**Comment by Nak0r** [comment]
Hi,

Thank you very much for your help. I indeed have a slightly better result now. I will let you know if I managed to improve it even further (by taking more genes as you mentioned).

Best,
Cedric

**Comment by Vivianstats** [comment]
Hello Cedric,

I'm closing this issue but feel free to open a new one if you have further questions.
