### ISSUE TITLE
reproducing result for the PBMC plot

### ISSUE THREAD

**Issue by radio1988** [Vivianstats/scImpute#14]
Hello Vivian, 

I'm trying to reproduce the PBMC plots you mentioned in your paper. Can the  4500 cell PBMC dataset be downloaded from this link: https://support.10xgenomics.com/single-cell-gene-expression/datasets/2.1.0/pbmc4k

Thanks!

**Comment by Vivianstats** [comment]
Hello,

Excuse me for the late reply. To collect data with true cell type labels, I randomly selected 500 cells from each purified dataset as listed [here](https://support.10xgenomics.com/single-cell-gene-expression/datasets):

![image](https://user-images.githubusercontent.com/25557722/39377903-a3f416d0-4a0b-11e8-96dc-ca43332fd791.png)
