### ISSUE TITLE
Question about input file

### ISSUE THREAD

**Issue by Gerde** [Vivianstats/scImpute#17]
Hi, Vivian, thank you for your work on scImpute package！I have a question about input count file, the input raw count file in quick start is /path/to/package/extdata/raw_count.csv, to my understanding, counts in this file should be an integer, but I see a float, did I misunderstand ?

**Comment by Vivianstats** [comment]
Hello Gerde,

The algorithm accepts both integers and floats. It is because some
pipelines will produce non-integer read counts when adjusting for
multiple alignment or other factors.
