### ISSUE TITLE
Differential gene expression analysis following imputation

### ISSUE THREAD

**Issue by eghorani** [Vivianstats/scImpute#20]
Dear Vivian,

Thanks very much for sharing this tool.......it's a very important contribution!

Regarding use of DESeq2 for differential gene expression analysis on the imputed data, did you round the imputed "counts" (as DESeq2 accepts integers only)? And did you use the package with standard parameters?

Finally, do you have any experience of using packages other than DESeq2/MAST on the output of scimpute?

Thanks very much

Ehsan

**Comment by Vivianstats** [comment]
Hello Ehsan,

Thanks for your interest in scImpute.

Yes, I rounded the counts to run DESeq2. I have only tried DESeq2 and MAST so far (using the standard parameters) and I expect other DE tools relying on similar assumptions and models should also work. What DE tools do you have in mind?

**Comment by eghorani** [comment]
Thanks for your reply Vivian

I found running rounded scimpute values through to DESeq2 produced some false positive results for genes that on manual inspection look very similar between conditions and switched to edgeR - that also has the advantage of running much faster. 

In a recent paper from Mark Robinson's lab (https://www.ncbi.nlm.nih.gov/pubmed/29481549) they found an edgeR implementation to be the best performing for single cell DE analysis. A formal analysis of DE tool performance on scimputed data could be a useful resource for the community........

Thanks again

Ehsan

**Comment by Vivianstats** [comment]
Hello Ehsan,

Thanks for the comments. I agree with you and will look into the integration with downstream analysis.

Best,
Vivian
