### ISSUE TITLE
Input/Output Options

### ISSUE THREAD

**Issue by bvieth** [Vivianstats/scImpute#3]
Dear Vivian,

thanks for making scImpute available. It works great for me. I just have a small question:
Could you maybe change the input and output options to R objects instead of only tsv/csv files? This would make it easier to include scImpute in my power simulation tool.

Kind regards,
Beate

**Comment by Vivianstats** [comment]
Hi Beate,

Thanks for your suggestion! I will incorporate these new features in the upcoming release.
