### ISSUE TITLE
Error in imputation

### ISSUE THREAD

**Issue by mohuangx** [Vivianstats/scImpute#4]
Hi Vivian,

I'm trying to run scImpute version 0.0.2, but it's giving me this error. I've included parts of my code and the error message below.

```R
library(scImpute)
count_path <- "data/Y4_033017.csv"
infile <- "csv"
outfile <- "csv"
out_dir <- "data/"
drop_thre <- 0.5
ncores <- 6
scimpute(count_path, infile, outfile, out_dir, drop_thre, ncores)
```
>[1] "reading in raw count matrix ..."
[1] "estimating mixture models ..."
[1] 500
[1] 1000
[1] 1500
[1] 2000
[1] 2500
[1] 3000
[1] 3500
[1] "imputing dropout values ..."
Error in type_list[[kk]] : subscript out of bounds

Thanks!
Mo

**Comment by Vivianstats** [comment]
Hi Mo,

Thanks your interest in the package. Could you provide an example data? Otherwise it's difficult to determine where the problem is.

**Comment by mohuangx** [comment]
Hi Vivian,

Thanks for the response. I'm attaching the dataset below.
[Y4_033017.csv.gz](https://github.com/Vivianstats/scImpute/files/1239135/Y4_033017.csv.gz)

Thanks,
Mo

**Comment by Vivianstats** [comment]
Hi Mo,

The reason of the error is that `scimpute ` also takes other arguments, so it is important to specify which arguments you refer to if you are not listing them in order. For example, you can try again with the following code
`
count_path <- "data/Y4_033017.csv"
out_dir <- "data/"
scimpute(count_path = count_path, infile = "csv", outfile = "csv", 
                out_dir = out_dir, drop_thre = 0.5, ncores = 10)`

Best,
Vivian

**Comment by mohuangx** [comment]
Thanks for the response! It is working now.
